# Generated by Django 6.0.6 on 2026-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado_adopcion',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'Adoptado')], default='1', max_length=20),
        ),
    ]
