# Generated by Django 6.0.6 on 2026-06-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_perro_imagen_alter_perro_estado_adopcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('texto', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
