# Generated by Django 6.0.6 on 2026-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
